apiVersion: v1
kind: Service
metadata:
  name: runmatic-postgres-headless
spec:
  clusterIP: None
  selector:
    app: runmatic-postgres
  ports:
    - port: 5432
      targetPort: 5432

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: runmatic-postgres
  namespace: default
spec:
  serviceName: "runmatic-postgres-headless"
  replicas: 1
  selector:
    matchLabels:
      app: runmatic-postgres
  template:
    metadata:
      labels:
        app: runmatic-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: runmatic-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: runmatic-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: runmatic-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: hostpath
        resources:
          requests:
            storage: 1Gi
