apiVersion: apps/v1
kind: Deployment
metadata:
  name: runmatic-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runmatic-postgres
  template:
    metadata:
      labels:
        app: runmatic-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
               configMapKeyRef:
                name: runmatic-config
                key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
               configMapKeyRef:
                name: runmatic-config
                key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
               secretKeyRef:
                name: runmatic-secrets
                key: POSTGRES_PASSWORD
