apiVersion: v1
kind: Secret
metadata:
 name: runmatic-secrets
 namespace: default
type: Opaque
data:
 DATABASE_URL: cG9zdGdyZXNxbCthc3luY3BnOi8vcnVubWF0aWM6ZGV2cGFzc3dvcmRAcG9zdGdyZXMtc2VydmljZTo1NDMyL3J1bm1hdGlj
 POSTGRES_PASSWORD: ZGV2cGFzc3dvcmQ=
 SECRET_KEY: ZGV2LXNlY3JldC1rZXk=
