FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
COPY alembic.ini .
RUN pip install --no-cache-dir  -r requirements.txt
COPY migrations ./migrations
EXPOSE 8000
COPY app ./app
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
